### ISSUE TITLE
ShopWired Integration Not Working?

### ISSUE THREAD

**Issue by WebSpectrum** [ideal-postcodes/shopwired#220]
Is this still working in current ShopWired version ? I followed the basic set up, but doesn't seem to be working

**Comment by cblanc** [comment]
Hi there, the issue pertains to the address fields on the user account creation page. While this currently isn't in scope, I've implemented a working integration for that page here in #221

**Comment by cblanc** [comment]
Fixed in #211 

Adding AV to the accounts pages via the templates looks viable, so thanks for that tip. I've added an issue at #223 to track that
